version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    environment:
      - JENKINS_USER=admin
      - JENKINS_PASS=password
      - DOCKER_HOST=tcp://host.docker.internal:2375
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always

  node:
    image: node:14
    container_name: node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: tail -f /dev/null

volumes:
  jenkins_home:
