version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"

  node-app:
    image: node:14
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - jenkins
    environment:
      - NODE_ENV=production

volumes:
  jenkins_home:
